### ISSUE TITLE
Neovim compatibility

### ISSUE THREAD

**Issue by mgoral** [LucHermitte/lh-vim-lib#10]
Hi,

does lh-vim-lib aim to be Neovim compatible? Currently I get an error that there's an undefined variable `v:none` used in [type.vim](https://github.com/LucHermitte/lh-vim-lib/blob/d21d1a377a195ea20fbb626e6f1ba63623b182e1/autoload/lh/type.vim#L66) and it seems that it was [removed](https://github.com/neovim/neovim/blob/master/runtime/doc/vim_diff.txt) from Neovim. What's your stance on this topic?

**Comment by LucHermitte** [comment]
Hi,

My stance is I don't strive to be absolutely compatible as I don't use NeoVim personnally -- i.e. I won't try to port my async autoload plugin for instance, nor to wrap/use neovim functions. I'm open to pull requests though -- I'll have to provide a CONTRIBUTORS files BTW.

Moreover, when fixes are easy to implement, I see no reason not to be compatible. In the case you've detected, I'll add a test on `exists('v:none')` tonight.

BTW: I'm already fighting to be compatible with old v7.3-429 that is installed on travis, or any later version. IOW, as far as I'm concerned, Vim is the reference.

**Comment by mgoral** [comment]
Fair enough and thanks for the fix! :)
