### ISSUE TITLE
lh#assert#mode documentation wrong

### ISSUE THREAD

**Issue by simlei** [LucHermitte/lh-vim-lib#14]
As per the documentation:
https://github.com/luchermitte/lh-vim-lib/blob/0c4d272a49f374723dd08c1e23570285b3146158/doc/lh-vim-lib.txt#L4798
the API user would expect to `call lh#assert#mode("abort")` and go on without the interactive assert stuff.
This fails with an exception (one that fails to be traced with lh#exception#say_what(), which makes it worse xD)

Grepping around, I found the correct value to set: "stop". Or is it the correct value?
Which should be the correct one in the end, the documented one conforming to the dbc stuff, or "stop"?
Please update doc & that line.
https://github.com/luchermitte/lh-vim-lib/blob/0c4d272a49f374723dd08c1e23570285b3146158/plugin/lhvl.vim#L63

----

While I'm here, I just have got to sing some praise.
Terrific library my man! It made vim script bearable for me and you explained OO really nicely! AND provided a way to use it without ending up in lambda debugging hell! And all those other features! e.g. the stacktrace decoder! Thanks so much! Vim really is a better tool with your library!

**Comment by LucHermitte** [comment]
Thank you for the feedback, and for the praise as well. I'm glad you like it.

In order to avoid changing the code, I've changed the documentation. 

BTW, thanks to `:h lhvl-:Toggle` feature, you can explore the valid values with `:Toggle PluginAssertmode` + `TAB`/`CTRL-D`
