### ISSUE TITLE
Duplicate tag in documentation

### ISSUE THREAD

**Issue by pborzenkov** [LucHermitte/lh-vim-lib#4]
Hi,

I'm seeing the following error while updated my vim plugins with plugged:

E154: Duplicate tag "lh#window#gotoid()" in file /Users/pbor/.vim/plugged/lh-vim-lib//doc/lh-vim-lib.txt

Looks like the same tag is listed twice for
lh#window#getid([{win}])~
and
lh#window#gotoid({id})~

I'm not really familiar with vim doc file format, so it would better if someone with more knowledge fixes this.

Thanks.

**Comment by LucHermitte** [comment]
Thank you.
