### ISSUE TITLE
Not an editor command: LetIfUndef g:cpp_inherits 'c'

### ISSUE THREAD

**Issue by sirmike** [LucHermitte/lh-vim-lib#6]
I am trying to use `lh-cpp` but when I open Vim, an error is displayed:

```
Error detected while processing /Users/SirMike/.vim/bundle/lh-vim-lib/autoload/lh/ft/option.vim:
line  138:
E492: Not an editor command: LetIfUndef g:cpp_inherits 'c'
```

Vim: 8.0.91
lh-vim, lh-brackets, lh-cpp, lh-dev, lh-tags are all from master for today

I reverted https://github.com/LucHermitte/lh-vim-lib/commit/8f0ce91fecdb4d3f12a47c2e17807d2c15c88769#diff-fc57e49cf28b941e6b291a4dfcb67499L127 and it started working again without errors. Is this a right solution or am I missing something important?

**Comment by LucHermitte** [comment]
No, you weren't missing anything. I was trying to fix an issue with Travis-CI. I have another one currently. I guess I'll to wait for the final v4.0.0 to fix it this time :(

Anyway, Thanks for the bug report. I've fixed the problem in a way a slightly more efficient compared to the old `:runtime plugin/let.vim`


Let me know if you observe any other issue.
