### ISSUE TITLE
Error detected while processing function lh#menu#def_toggle_item[47]..<SNR>52_Set

### ISSUE THREAD

**Issue by Qiguang** [LucHermitte/lh-vim-lib#7]
Hi, I use your local vimrc plugin. And it's good. But I found it cannot work recently.
Maybe after I upgrade to Vim 8.0, I'm not sure.
I only wrote 2 commands in _vimrc_local.vim

-  cd /XXXX/XXXX/XXXX/the/path/

this command works well.
but the 2nd command cannot work:

- set tags=./tags,../../Common/tags,../../../../shared/inc/tags.

And then I updated the plugins by Vundle.
After that, when I open vim, it says:
**Error detected while processing function lh#menu#def_toggle_item[47]..<SNR>52_Set:
line   33:
E605: Exception not caught: Cannot set: lh#project.auto_discover_root=in_doubt_ask: Vim(let):E121: Undefined variable: g:lh#project in function lh#menu#def_toggle_item[47]..<SNR>52_Set, line 13
Press ENTER or type command to continue**
BTW, I use Vim in MSYS environment.

**Comment by LucHermitte** [comment]
Hi.

I've refactored a few things lately. It seems to come from this. Let me know if you are still experimenting the issue.

Note BTW that if you're changing directory to the root of your project, it can be handled by this new Project feature from lh-vim-lib that's messing your configuration.
